# -*- coding: utf-8 -*-
"""Copy of Vsualisation of PyCK_RF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lAJmJMVztnQYUiRYM5C5SxieMl79JbzX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn

from google.colab import drive
drive.mount('/content/drive')

path = "drive/My Drive/CombinedInput.xlsx"
df = pd.read_excel(path)

df.head()

df.columns

df.rename({'Unnamed: 0':'Labels'},axis = 1, inplace=True)

df.head()

df.shape

df.columns

X = df.iloc[:,1:].values
y = df.iloc[:,0].values

X

X.shape

y

import seaborn as sn; sn.set_theme()

plt.pcolor(X)

X.shape
X1=np.transpose(X)
X1.shape
data=X1[1]
data_1=data[0:11]
data_2=data[11:]

import matplotlib.pyplot as plt
import numpy as np
 
 
# Creating dataset
np.random.seed(10)
 

data = [data_1, data_2]
 
fig = plt.figure(figsize =(10, 7))
 
# Creating axes instance
ax = fig.add_axes([1, 0, 1, 1])
 
# Creating plot
bp = ax.boxplot(data)
 
# show plot
plt.show()

X.shape

# plotting the heatmap
hm = sn.heatmap(data = X)
  
# displaying the plotted heatmap
plt.show()